### ISSUE TITLE
Contact Address

### ISSUE THREAD

**Issue by thomask77** [rampadc/cc2540-hidKbdM#1]
Hi Cong!

I couldn't find any contact address, so I'm trying it here.. can you please contact me at mail_1501@t-kindler.de? I have a question about the ThinkPad keyboard connectors!

**Comment by thomask77** [comment]
Any news? I'd like to buy some connectors from you, if you still have some left.

**Comment by rampadc** [comment]
No I don't have any left.

**Comment by thomask77** [comment]
Ah, thanks for the information.
Where did you order yours?

Also, you might be interested in my project:
    https://github.com/thomask77/nucular-keyboard

best regards,
Thomas!
